export const AGREGAR_FAVORITOS = 'AGREGAR_FAVORITOS';
export const ELIMINAR_FAVORITOS = 'ELIMINAR_FAVORITOS';
export const DATA_COMPLETA = 'DATA_COMPLETA';
export const DATA_A_MOSTRAR = 'DATA_A_MOSTRAR';
export const NUMERO_PAGINA = 'NUMERO_PAGINA';
